name: blade
version: develop
version-script: git describe --exact-match --tags 2> /dev/null || echo "develop"
summary: The Blade Smart-Contract Programming-Language
description: |
  The Blade EVM smart-contract language. Blade comes with drop-in support for all existing Solidity dApps plus compile-time zkp using PLONKY2 and Circom Prooving Software.
grade: stable
confinement: strict

apps:
  blade:
    command: blade
    plugs: [home]

parts:
  solidity:
    source: .
    source-type: git
    plugin: cmake
    build-packages: [build-essential, libboost-all-dev, libz3-dev]
    stage-packages: [libicu55]
    prepare: |
      if git describe --exact-match --tags 2> /dev/null
      then
        echo -n > ../src/prerelease.txt
      fi
